### ISSUE TITLE
展示效果不一致

### ISSUE THREAD

**Issue by DelmarHuang** [napretep/hjp-bilink#1]
你好，请问为什么我的双向链接是这样😂我选了5张卡，然后点了完全图链接。跟你去年发的视频完全不一样。请问怎么解决？
https://www.zhihu.com/zvideo/1340373875801280512

是因为你视频里说的第二个插件安装不上的问题么？因为我用的是最新版的anki，然后提示我564851917这个插件无法安装

麻烦你了，谢谢！

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54244063/180653383-eaff6106-1994-4dce-9735-2f3626054f64.png">

**Comment by napretep** [comment]
这个内容已经过期了, 不要安上面的方法工作

**Comment by DelmarHuang** [comment]
> 这个内容已经过期了, 不要安上面的方法工作

那请问有最新的演示视频么😂我看你知乎并没有更新。然后只看到一篇文章，根据那边文章，我想用视图管理器给多张卡片添加链接，但是发生了错误。是不是Mac的问题？报错如下，麻烦你了！

```
错误
发生了一个错误。请在启动Anki时按住「Shift」键临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki， 请重复上述步骤直至找到引起错误的插件。 找到引起错误的插件后，请反馈给插件作者。 调试信息：
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.0
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-25 21:59:56
相关插件：⁨hjp-bilink  make the disorganized card more organizable⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/delmar/Library/Application Support/Anki2/addons21/1420819673/lib/bilink/dialogs/linkdata_grapher.py", line 546, in mouseMoveEvent
    p1_1=common_tools.funcs.Geometry.IntersectPointByLineAndRect(QLineF(p1,p2),rect)
  File "/Users/delmar/Library/Application Support/Anki2/addons21/1420819673/lib/common_tools/funcs.py", line 2628, in IntersectPointByLineAndRect
    if line.intersect(edge, intersectPoint) == QLineF.BoundedIntersection:
AttributeError: 'QLineF' object has no attribute 'intersect'

```

**Comment by napretep** [comment]
> 

那篇文章是怎么操作的
